In [358]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as pit
import seaborn as sns
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/diabetes-data-set/diabetes.csv


In [359]:
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [360]:
df = pd.read_csv("/kaggle/input/diabetes-data-set/diabetes.csv")

In [361]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [362]:
df.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [363]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [364]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [365]:
x = df.drop(['Outcome'], axis=1)
y = df[['Outcome']]

In [366]:
trainX, testX, trainY, testY = train_test_split(x,y, test_size=0.2)

In [367]:
dtc=DecisionTreeClassifier()
dtc.fit(trainX, trainY)

DecisionTreeClassifier()

In [368]:
y_predicted = dtc.predict(testX)

In [369]:
confusion_matrix(testY,y_predicted)

array([[77, 20],
       [28, 29]])

In [370]:
tp= 76
fn = 20
fp = 27
tn = 31
precision = tp/(tp+fp)
recall = tp/(tp+fn)
specificify = tn/(fp+tn)
f1 = 2 * (precision*recall)/(precision+recall)
print ("Precision: " ,precision) 
print ("Recall: ",recall),
print ("Specificity: ",specificify)
print ("F1 score: ",f1)

Precision:  0.7378640776699029
Recall:  0.7916666666666666
Specificity:  0.5344827586206896
F1 score:  0.7638190954773869


In [371]:
svm=SVC(kernel='linear')
svm.fit(trainX, trainY.values.ravel())

SVC(kernel='linear')

In [372]:
y_predicted = svm.predict(testX)

In [373]:
tp = 67
fn = 27
fp = 9
tn = 100

precision = tp/ (tp+fp)
recall = tp/(tp+fn)
specificity = tn/(fp+tn)
f1 = 2* (precision*recall)/(precision+recall)
precision,recall, specificity,f1

(0.881578947368421, 0.7127659574468085, 0.9174311926605505, 0.788235294117647)

In [374]:
nb = GaussianNB()
nb.fit(trainX, trainY.values.ravel())

GaussianNB()

In [375]:
y_predicted = nb.predict(testX)

In [376]:
confusion_matrix(testY,y_predicted)

array([[83, 14],
       [23, 34]])

In [377]:
tp = 88
fn = 8
fp = 26
tn = 32
precision = tp/(tp+fp)
recall=tp/(tp+fn)
specificity = tn/(fp+tn)
fl= 2*(precision*recall)/(precision+recall)
precision, recall, specificity, f1

(0.7719298245614035, 0.9166666666666666, 0.5517241379310345, 0.788235294117647)

In [378]:
rf = RandomForestClassifier()
rf.fit(trainX, trainY.values.ravel())

RandomForestClassifier()

In [379]:
y_predicted=svm.predict(testX)
y_actual=testY

In [380]:
confusion_matrix(testY,y_predicted)

array([[87, 10],
       [27, 30]])

In [381]:
tp = 90
fn = 6
fp = 29
tn = 29
precision = tp/(tp+fp)
recall = tp/(tp+fn)
specificity = tn/(fp+tn)
f1= 2*(precision*recall)/(precision+recall)
print ("Precision: " ,precision) 
print ("Recall: ",recall),
print ("Specificity: ",specificity)
print ("F1 score: ",f1)


Precision:  0.7563025210084033
Recall:  0.9375
Specificity:  0.5
F1 score:  0.8372093023255813
